### ISSUE TITLE
Spawning of BoltAbilityProjectile occassionally crashes the game.

### ISSUE THREAD

**Issue by AndrewDoesNotCompute** [rtcothern/Bruin_Game_Studios_Team-Moba#5]
This issue occurs when a newly spawning BoltAbilityProjectile collides with an Interactable before its Source field can be set. This is because the blueprint destroys the actor immediately after it has collided with another

AbilityComponent.cpp/CastProjectile():

```
//sometimes destroyed here, so it returns a null reference!
AAbilityProjectile *Projectile = (AAbilityProjectile*)(GetWorld()->SpawnActor(AbilityProjectileClass, &Start, &Rotation)); 

//attempting to dereference a null pointer!
Projectile->SetSource(GetCaster()); 
```

**Comment by rtcothern** [comment]
Fixed in commit 46ea77bb95f0c59748ba786505ac76c529814e7
